server:
  port: 9090
spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/muxinke/myconfig.git
          search-paths: mydirect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka