
spring:
  application:
    name: provider-server-10003
  profiles:
    active: 10003
  cloud:
    config:
      discovery:
        service-id: server-config
        enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.107.15.222:3306/easydai?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 971103
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 10003